const positions = [
    {id: 111, s: 1, e: 1, name: 'Tipo de registro', description: 'Identificação do registro header', default: '0'},
    {id: 122, s: 2, e: 2, name: 'Código de retorno', description: 'Identificação do arquivo retorno', default: '2'},
    {id: 139, s: 3, e: 9, name: 'Literal de retorno', description: 'Identificação por extenso do tipo de movimento', default: 'RETORNO'},
    {id: 11011, s: 10, e: 11, name: 'Código do retorno', description: 'Identificação do tipo de serviço', default: '01'},
    {id: 11226, s: 12, e: 26, name: 'Literal de serviço', description: 'Identificação por extenso do tipo de serviço', default: 'COBRANCA'},
    {id: 12730, s: 27, e: 30, name: 'Agência', description: 'Agência mantenedora da conta', default: null},
    {id: 13132, s: 31, e: 32, name: 'Zeros', description: 'Complemento de registro', default: '00'},
    {id: 13337, s: 33, e: 37, name: 'Contas', description: 'Número da conta corrente da empresa', default: null},
    {id: 13838, s: 38, e: 38, name: 'DAC', description: 'Dígito de auto conferência ag/conta empresa', default: null},
    {id: 13946, s: 39, e: 46, name: 'Brancos', description: 'Complemento do registro', default: null},
    {id: 14776, s: 47, e: 76, name: 'Nome da empresa', description: 'Nome por extenso da "Empresa mãe"', default: null},
    {id: 17779, s: 77, e: 79, name: 'Código do banco', description: 'Número do banco na câmara de compensação', default: '341'},
    {id: 18094, s: 80, e: 94, name: 'Nome do banco', description: 'Nome por extenso do banco cobrador', default: 'BANCO ITAU S.A.'},
    {id: 195100, s: 95, e: 100, name: 'Data de geração', description: 'Data de geração do arquivo', default: null},
    {id: 1101105, s: 101, e: 105, name: 'Densidade', description: 'Unidade da densidade', default: null},
    {id: 1106108, s: 106, e: 108, name: 'Unidade de densid.', description: 'Densidade de gravação do arquivo', default: 'BPI'},
    {id: 1109113, s: 109, e: 113, name: 'Nº seq. arquivo ret.', description: 'Número seqüencial do arquivo retorno', default: null},
    {id: 1114119, s: 114, e: 119, name: 'Data de crédito', description: 'Data de crédito dos lançamentos', default: null},
    {id: 1120394, s: 120, e: 394, name: 'Brancos', description: 'Complemento do registro', default: null},
    {id: 1394400, s: 395, e: 400, name: 'Número seqüencial', description: 'Número seqüencial do registro no arquivo', default: '000001'}
];

const itau400retTemplate = [
    {
        id: 1,
        description: 'Registro header de arquivo',
        optional: false,
        positions: [
            {id: 111, s: 1, e: 1, name: 'Tipo de registro', description: 'Identificação do registro header', default: '0'},
            {id: 122, s: 2, e: 2, name: 'Código de retorno', description: 'Identificação do arquivo retorno', default: '2'},
            {id: 139, s: 3, e: 9, name: 'Literal de retorno', description: 'Identificação por extenso do tipo de movimento', default: 'RETORNO'},
            {id: 11011, s: 10, e: 11, name: 'Código do retorno', description: 'Identificação do tipo de serviço', default: '01'},
            {id: 11226, s: 12, e: 26, name: 'Literal de serviço', description: 'Identificação por extenso do tipo de serviço', default: 'COBRANCA'},
            {id: 12730, s: 27, e: 30, name: 'Agência', description: 'Agência mantenedora da conta', default: null},
            {id: 13132, s: 31, e: 32, name: 'Zeros', description: 'Complemento de registro', default: '00'},
            {id: 13337, s: 33, e: 37, name: 'Contas', description: 'Número da conta corrente da empresa', default: null},
            {id: 13838, s: 38, e: 38, name: 'DAC', description: 'Dígito de auto conferência ag/conta empresa', default: null},
            {id: 13946, s: 39, e: 46, name: 'Brancos', description: 'Complemento do registro', default: null},
            {id: 14776, s: 47, e: 76, name: 'Nome da empresa', description: 'Nome por extenso da "Empresa mãe"', default: null},
            {id: 17779, s: 77, e: 79, name: 'Código do banco', description: 'Número do banco na câmara de compensação', default: '341'},
            {id: 18094, s: 80, e: 94, name: 'Nome do banco', description: 'Nome por extenso do banco cobrador', default: 'BANCO ITAU S.A.'},
            {id: 195100, s: 95, e: 100, name: 'Data de geração', description: 'Data de geração do arquivo', default: null},
            {id: 1101105, s: 101, e: 105, name: 'Densidade', description: 'Unidade da densidade', default: null},
            {id: 1106108, s: 106, e: 108, name: 'Unidade de densid.', description: 'Densidade de gravação do arquivo', default: 'BPI'},
            {id: 1109113, s: 109, e: 113, name: 'Nº seq. arquivo ret.', description: 'Número seqüencial do arquivo retorno', default: null},
            {id: 1114119, s: 114, e: 119, name: 'Data de crédito', description: 'Data de crédito dos lançamentos', default: null},
            {id: 1120394, s: 120, e: 394, name: 'Brancos', description: 'Complemento do registro', default: null},
            {id: 1394400, s: 395, e: 400, name: 'Número seqüencial', description: 'Número seqüencial do registro no arquivo', default: '000001'}
        ]
    },
    {
        id: 2,
        description: 'Registro detalhe de arquivo',
        optional: false,
        positions: [
            {id: 211, s: 1, e: 1, name: 'Tipo de registro', description: 'Identificação do registro transação', default: '1'},
            {id: 223, s: 2, e: 3, name: 'Código de inscrição', description: 'Identificação do tipo de inscrição/empresa', default: null, options: [{ content: '01', description: 'CPF' }, { content: '02', description: 'CNPJ' }]},
            {id: 2417, s: 4, e: 17, name: 'Número de inscrição', description: 'Número de inscrição da empresa (CPF/CNPJ)', default: null},
            {id: 21821, s: 18, e: 21, name: 'Agência', description: 'Agência mantenedora da conta', default: null},
            {id: 22223, s: 22, e: 23, name: 'Zeros', description: 'Complemento de registro', default: '00'},
            {id: 22428, s: 24, e: 28, name: 'Conta', description: 'Número da conta corrente da empresa', default: null},
            {id: 22929, s: 29, e: 29, name: 'DAC', description: 'Dígito de auto conferência ag/conta empresa', default: null},
            {id: 23037, s: 30, e: 37, name: 'Brancos', description: 'Complemento de registro', default: null},
            {id: 23862, s: 38, e: 62, name: 'Uso da empresa', description: 'Identificação do título na empresa', default: null},
            {id: 26370, s: 63, e: 70, name: 'Nosso número', description: 'Identificação do título no banco', default: null},
            {id: 27182, s: 71, e: 82, name: 'Brancos', description: 'Complemento do registro', default: null},
            {id: 28385, s: 83, e: 85, name: 'Carteira', description: 'Número da carteira', default: null},
            {id: 28693, s: 86, e: 93, name: 'Nosso número', description: 'Identificação do título no banco', default: null},
            {id: 29494, s: 94, e: 94, name: 'DAC nosso número', description: 'DAC do nosso número', default: null},
            {id: 295107, s: 95, e: 107, name: 'Brancos', description: 'Complemento do registro', default: null},
            {id: 2108108, s: 108, e: 108, name: 'Carteira', description: 'Código da carteira', default: null},
            {id: 2109110, s: 109, e: 110, name: 'Cód. de ocorrência', description: 'Identificação da ocorrência', default: null},
            {id: 2111116, s: 111, e: 116, name: 'Data de ocorrência', description: 'Data de ocorrência no banco', default: null},
            {id: 2117126, s: 117, e: 126, name: 'Nº do documento', description: 'Nº do documento de cobrança (dupl, np e etc)', default: null},
            {id: 2127164, s: 127, e: 134, name: 'Nosso número', description: 'Confirmação do número do título no banco', default: null},
            {id: 2135146, s: 135, e: 146, name: 'Brancos', description: 'Complemento do registro', default: null},
            {id: 2147152, s: 147, e: 152, name: 'Vencimento', description: 'Data de vencimento do título', default: null},
            {id: 2153165, s: 153, e: 165, name: 'Valor do título', description: 'Valor nominal do título', default: null},
            {id: 2166168, s: 166, e: 168, name: 'Código do banco', description: 'Número do banco na câmara de compensação', default: null},
            {id: 2169172, s: 169, e: 172, name: 'Agência cobradora', description: 'Ag. cobradora, ag. de liquidação ou baixa', default: null},
            {id: 2173173, s: 173, e: 173, name: 'DAC ag. cobradora', description: 'DAC da agência cobradora', default: null},
            {id: 2174175, s: 174, e: 175, name: 'Espécie', description: 'Espécie do título', default: null},
            {id: 2176188, s: 176, e: 188, name: 'Tarifa de cobrança', description: 'Valor da despesa de cobrança', default: null},
            {id: 2189214, s: 189, e: 214, name: 'Brancos', description: 'Complemento do registro', default: null},
            {id: 2215227, s: 215, e: 227, name: 'Valor do IOF', description: 'Valor do IOF a ser recolhido (notas seguro)', default: null},
            {id: 2228240, s: 228, e: 240, name: 'Valor abatimento', description: 'Valor do abatimento concedido', default: null},
            {id: 2241253, s: 241, e: 253, name: 'Descontos', description: 'Valor do desconto concedido', default: null},
            {id: 2254266, s: 254, e: 266, name: 'Valor principal', description: 'Valor lançado em conta corrente', default: null},
            {id: 2267279, s: 267, e: 279, name: 'Juros de mora/multa', description: 'Valor de mora e multa', default: null},
            {id: 2280292, s: 280, e: 292, name: 'Outros créditos', description: 'Valor de outros créditos', default: null},
            {id: 2293293, s: 293, e: 293, name: 'Boleto DDA', description: 'Indicador de boleto DDA', default: null},
            {id: 2294295, s: 294, e: 295, name: 'Brancos', description: 'Complemento do registro', default: null},
            {id: 2296301, s: 296, e: 301, name: 'Data crédito', description: 'Data de crédito desta liquidação', default: null},
            {id: 2302305, s: 302, e: 305, name: 'Instr. Cancelada', description: 'Código da instrução cancelada', default: null},
            {id: 2306311, s: 306, e: 311, name: 'Brancos', description: 'Complemento do registro', default: null},
            {id: 2312324, s: 312, e: 324, name: 'Zeros', description: 'Complemento de registro', default: null},
            {id: 2325354, s: 325, e: 354, name: 'Nome do pagador', description: 'Nome do pagador', default: null},
            {id: 2355377, s: 355, e: 377, name: 'Brancos', description: 'Complemento do registro', default: null},
            {id: 2378385, s: 378, e: 385, name: 'Erros/Mensagem informativa', description: 'Registros rejeitados ou alegação do pagador ou registro de mensagem informativa', default: null},
            {id: 2386392, s: 386, e: 392, name: 'Brancos', description: 'Complemento do registro', default: null},
            {id: 2393394, s: 393, e: 394, name: 'Cód. de liquidação', description: 'Meio pelo qual o título foi liquidado', default: null},
            {id: 2395400, s: 395, e: 400, name: 'Número seqüencial', description: 'Número seqüencial do registro no arquivo', default: null},
        ]
    }
]
